server:
  port: 80
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ureasolution
    username: jerry
    password: dngudrkwmdk!!
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.SQL: error
dataportal:
  servicekey: OPnntQNdcjd1m2Dekuq/1FYtDBm8I6Y9kc2m88ol10qpE5BvY31fWpG7dqJSVS1cryrz/u1nNPWt7S6tWL3cwA==
